### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by HuntFeng** [sophosia/sophosia#159]
The following features / improvements will be added (in random orders depending on how easy or difficult to implement) in the future updates. 

- [x] #174
- [ ] shortcuts
- [ ] task management system
- [ ] better pdf reader
- [ ] more citation format
- [ ] web connector for pdf
- [ ] word/google doc integration
- [ ] useful plugin system
- [ ] graphRAG
- [ ] useful documentation
- [ ] OCR pdf
- [ ] support attaching EPUB files and possibly other file types
